scripts:
  - name: Install Dependencies
    script: |
      npm install
      npm run build || echo "No build script found"

  - name: Add Android platform
    script: |
      npx cap add android

  - name: Sync Capacitor
    script: |
      npx cap sync android

  - name: Build APK
    script: |
      cd android
      ./gradlew assembleDebug
