workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.rezzdev.myapp"
      node: 20.11.1
      java: 17
    scripts:
      - name: Install Dependencies
        script: |
          npm install
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
